# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

# See https://snakemake.readthedocs.io/en/stable/executing/cli.html#profiles

# logger: pypsa  # Removed - not compatible with Snakemake 8.x
