# SPDX-FileCopyrightText: 2026 Aleksander Grochowicz
#
# SPDX-License-Identifier: MIT

"""
Solve one batch of near-optimal directions on one node.

This script is called by snakemake once per batch, with batches distributed
across multiple SLURM nodes for parallel solving. Directions are loaded from
JSON files generated by generate_near_opt_directions.py.

See: documentation/pypsa-eur/mga-multi-node-parallelization.md
"""

import logging

import numpy as np
import pandas as pd
import pypsa

from _helpers import (
    configure_logging,
    set_scenario_config,
    update_config_from_wildcards,
)
from compute_near_opt import (
    combine_results,
    fill_dimension_weights,
    load_dimensions_from_config,
)
from mga_helpers import export_mga_capacities
from solve_second_network import fix_networks

logger = logging.getLogger(__name__)


if __name__ == "__main__":
    if "snakemake" not in globals():
        from _helpers import mock_snakemake

        snakemake = mock_snakemake(
            "compute_near_opt_batch",
            opts="",
            clusters="50",
            batch_hash="test",
            configfiles="config/mini-sector_droughts.yaml",
        )

    configure_logging(snakemake)
    set_scenario_config(snakemake)
    update_config_from_wildcards(snakemake.config, snakemake.wildcards)

    batch_hash = snakemake.wildcards.batch_hash
    logger.info(f"Starting batch {batch_hash}")

    # Load network
    logger.info(f"Loading network from {snakemake.input.network}")
    n = pypsa.Network(snakemake.input.network)
    m = n.copy()

    # Fix network to prevent transmission expansion
    logger.info("Fixing network capacities")
    fix_networks(m, n)

    # Load near-opt configuration
    mga_config = snakemake.config.get("near-opt", {})
    if not mga_config:
        raise ValueError("No 'near-opt' configuration found in config file")

    # Compute slack
    slack_config = mga_config.get("slack", {})
    if slack_config.get("relative", True):
        slack = slack_config.get("value", 0.05)
        logger.info(f"Using relative slack: {slack}")
    else:
        absolute_slack = float(slack_config.get("value", 0.0))
        if not hasattr(n, "objective"):
            raise ValueError("Network has no objective value. Run optimisation first.")
        obj = n.objective
        if isinstance(obj, (pd.Series, pd.DataFrame)):
            objective_value = float(obj.sum())
        elif isinstance(obj, np.ndarray):
            objective_value = float(obj.sum())
        else:
            objective_value = float(obj)
        if objective_value == 0:
            raise ValueError("Network objective is zero.")
        slack = float(absolute_slack) / float(objective_value)
        logger.info(f"Using absolute slack: {absolute_slack} (relative: {slack})")

    # Load and fill dimensions
    logger.info("Loading projection dimensions from config")
    config_projection = mga_config.get("projection", {})
    dimensions = load_dimensions_from_config(config_projection)
    dimensions = fill_dimension_weights(m, dimensions)

    # Load this batch's directions from JSON files
    batch_directions = []
    for dir_file in snakemake.input.direction_files:
        direction = pd.read_json(dir_file, typ="series")
        batch_directions.append(direction)

    directions_df = pd.DataFrame(batch_directions).reset_index(drop=True)
    batch_size = len(directions_df)
    logger.info(f"Batch {batch_hash}: loaded {batch_size} directions")

    # Get solver configuration
    solver_config = snakemake.config.get("solving", {})
    solver_name = solver_config.get("solver", {}).get("name", "gurobi")
    solver_options = solver_config.get("solver_options", {}).get(
        solver_config.get("solver", {}).get("options", "default"), {}
    )
    cache_dir = mga_config.get("cache_dir", None)

    logger.info(f"Using solver: {solver_name}, cache_dir: {cache_dir}")

    # Run near-opt optimisation for this batch
    successful_directions, successful_coordinates = (
        m.optimize.optimize_mga_in_multiple_directions(
            directions=directions_df,
            dimensions=dimensions,
            cache_dir=cache_dir,
            mga_extra_functionality=export_mga_capacities,
            snapshots=None,
            multi_investment_periods=False,
            slack=slack,
            model_kwargs=None,
            max_parallel=batch_size,
            solver_name=solver_name,
            solver_options=solver_options,
        )
    )

    n_successful = len(successful_directions)
    n_failed = batch_size - n_successful
    if n_failed > 0:
        logger.error(f"Batch {batch_hash}: {n_failed}/{batch_size} directions FAILED")
        raise RuntimeError(
            f"Batch {batch_hash} failed: {n_failed} directions unsuccessful"
        )

    logger.info(f"Batch {batch_hash}: all {n_successful} directions successful")

    # Combine and save batch results
    batch_results = combine_results(successful_directions, successful_coordinates)
    batch_results.to_csv(snakemake.output.batch_result, index=False)

    logger.info(f"Batch {batch_hash}: results saved to {snakemake.output.batch_result}")
